name: Limited Dastardly Security Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dastardly_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Burp Configuration File (Limits Crawling)
        run: |
          cat <<EOF > burp-config.json
          {
            "target": {
              "scope": {
                "include": [
                  {"rule": "https://demo.testfire.net/*"}
                ],
                "exclude": []
              }
            },
            "crawl": {
              "maxLinks": 10,  # Limit crawl to 10 URLs
              "maxDuration": 120  # Optional: Stop scan after 5 minutes (300 sec)
            }
          }
          EOF

      - name: Run Dastardly Scan with Limited Crawling
        uses: PortSwigger/dastardly-github-action@main
        with:
          target-url: "https://demo.testfire.net/"
          burp-config: "burp-config.json"
          output-file: dastardly_output.log

      - name: Convert Dastardly Output to Markdown
        run: |
          echo "# Dastardly Security Scan Report" > dastardly_report.md
          echo "## Scan Results (Limited to 10 URLs)" >> dastardly_report.md
          echo "\`\`\`" >> dastardly_report.md
          cat dastardly_output.log >> dastardly_report.md
          echo "\`\`\`" >> dastardly_report.md

      - name: Convert Markdown to HTML
        run: |
          sudo apt-get update && sudo apt-get install -y pandoc
          pandoc dastardly_report.md -o dastardly_report.html

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dastardly_html_report
          path: dastardly_report.html

      - name: Provide Direct Download Link
        run: |
          echo "### 📥 [Download Dastardly Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts) 🚀" >> $GITHUB_STEP_SUMMARY
